### ISSUE TITLE
Helm chart | non existing docker image

### ISSUE THREAD

**Issue by HBO2** [presslabs/mysql-operator#128]
The helm chart on https://presslabs.github.io/charts is pointing to mysql-operator image with tag 0.2.0 which is non existing

**Comment by AMecea** [comment]
I've updated the charts repository to point to the right version. And also I've bumped chart version to `v0.1.13` that contains latest master commits. The version 2 of the chart slipped accidentally into the charts repository. 

Can you please check if it works?

Thank you for letting us know about this issue.

**Comment by AMecea** [comment]
I don't use minio but I searched through their [docs](https://github.com/minio/cookbook/blob/master/docs/rclone-with-minio.md) and found out that rclone can be configured with minio. [Rclone](https://rclone.org/) is the tool that we used  to handle storage actions. Rclone configuration file is generated [here](https://github.com/presslabs/mysql-operator/blob/master/hack/docker/mysql-helper/docker-entrypoint.sh#L5).

You have to specify the endpoint (`S3_ENDPOINT`) in the backup secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-backup-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: # your access_key, base64 encoded
  AWS_SECRET_KEY: # your secret_key, base64 encoded
  AWS_REGION: # region(should be specified, see documentation), base64 encoded
  S3_ENDPOINT: # put here your endpoint [servicename].default.svc.cluster.local base64 encoded
```

and the `backupUri` should look something like: `gs://bucket/path/`.

Please let me know if this works or not. Hope this helps.
