### ISSUE TITLE
Creating cluster with 'volumeSpec' does not include default storageClass

### ISSUE THREAD

**Issue by kalium99** [presslabs/mysql-operator#168]
Not sure if this is a bug or expected behaviour (perhaps the latter), but I copied the example in the docs for the optional volumeSpec, modifying only the value for storage:
```
volumeSpec:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 20Gi
```
This fails though due to having no `storageClassName` (which took me a few minutes to work out). I guess I should have known better, but maybe even mentioning storageClassName in the example docs may help (or even adding adding default storageClassName if none is present?).
