### ISSUE TITLE
Enable backups for existing cluster

### ISSUE THREAD

**Issue by micronax** [presslabs/mysql-operator#182]
Is there any way to enable backups for a existing cluster or do I need to recreate the cluster with the `backupSchedule` specs?

At least the README is unclear at this point.

**Comment by HBO2** [comment]
@AMecea I am not sure, but I think the scheduled backup it still not working right? I am using the latest operator. and confirmed the backup it self is working, but scheduling in the cluster seems not to work because the cron trigger is doing noting:

```
....
spec:
  backupSchedule: 0 0 */20 * * *
  backupScheduleJobsHistoryLimit: 1
  backupSecretName: my-cluster-backup-secret
  backupUri: s3://backup/
....
```
