### ISSUE TITLE
Changing config might cause blocking delete.

### ISSUE THREAD

**Issue by bluven** [presslabs/mysql-operator#197]
First I created a cluster, then I wanted to try to configure slow logs, so I changed config and applied the change. But I made some errors, here is the code:
```
 mysqlConf:
    slow_query_log: 1
    log_output: table
    long_query_time: 20
    slow_query_log_file: /var/log/mysql/log-slow-queries.log
```

I checked configmap, nothing changed. So I decied to delete this cluster, but it didn't work as it is blocked.

I checked mysql-operator log, it  kept complaining:

> E0111 08:42:36.541029       1 reflector.go:205] github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha1.MysqlCluster: v1alpha1.MysqlClusterList.Items: []v1alpha1.MysqlCluster: v1alpha1.MysqlCluster.Spec: v1alpha1.MysqlClusterSpec.MysqlConf: ReadString: expects " or n, but found 2, error found in #10 byte of ...|ry_time":20,"slow_qu|..., bigger context ...|sqlConf":{"log_output":"table","long_query_time":20,"slow_query_log":1,"slow_query_log_file":"/var/l|

After correcting config to this:

```
mysqlConf:
    slow_query_log: "1"
    log_output: table
    long_query_time: "20"
    slow_query_log_file: /var/log/mysql/log-slow-queries.log
```

The blocked deletion succeed.

I tried used error config to create cluster, this won't cause a blocked deletion.
