### ISSUE TITLE
Failed to initialize root password and custom user/password.

### ISSUE THREAD

**Issue by bluven** [presslabs/mysql-operator#229]
I created a mysql cluster, but the generated mysql cluster didn't initialize root with specifyed password and custom user/password were neither initialized.

mysql-operator: 0.2.2
```
mysql> select user, host from mysql.user;
+--------------+-----------+
| user         | host      |
+--------------+-----------+
| orchestrator | %         |
| repl_McYOj   | %         |
| exp_dnuFW    | 127.0.0.1 |
| root         | localhost |
+--------------+-----------+
```

cluster.yaml
```yaml
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mc
spec:
  # image: percona:5.7.24
  replicas: 2
  secretName: my-secret

  mysqlConf:
    slow_query_log: "1"
    log_output: table
    long_query_time: "20"
    slow_query_log_file: /dev/stdout

  podSpec:
     resources:
       requests:
         memory: 256Mi
         cpu:    200m

  ## Specify additional volume specification
  volumeSpec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 1Gi
```

secret.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default
type: Opaque
data:
  # root password is required to be specified
  ROOT_PASSWORD: cm9vdA==
  USER: Ymx1dmVu
  PASSWORD: eWFuc2hpeWk=
```

Partial of mysql node env
```
MYSQL_PASSWORD=yanshiyi
MYSQL_OPERATOR_TEST_ORCHESTRATOR_PORT=tcp://10.102.244.101:80
MYSQL_ROOT_PASSWORD=root
MYSQL_USER=bluven
```
