### ISSUE TITLE
Backup names do not include `metadata.name`

### ISSUE THREAD

**Issue by ballad89** [presslabs/mysql-operator#253]
```yml
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlBackup
metadata:
  namespace: test-namespace
  name: baseline
spec:
  clusterName: mysql-cluster
```
Currently the above backup would be named `mysql-cluster-<date>...` on s3.
I think the name of the backup should be included in the name such as `mysql-cluster-baseline-<date>...` as it would provide a way to identify and differentiate backups.
Or it can even be called `baseline-<date>...` as that is the name specified.
In summary, a way to control what my snapshots are called would be nice
