### ISSUE TITLE
Add support for PodSecurityPolicy

### ISSUE THREAD

**Issue by surajssd** [presslabs/mysql-operator#258]
Add support of Pod Security Policy in the operator. Right now it is not possible to deploy the operator that has PSP enabled in it.

**Comment by AMecea** [comment]
Hi @surajssd, thank you for opening this issue!

The problem is with the docker images that run the processes as root.  There are few places where it needs to tweak the Dockerfiles and maybe helm charts. One of them is [orchestrator chart](https://github.com/presslabs/docker-orchestrator) and in the sidecar [Dockerfile](https://github.com/presslabs/mysql-operator/blob/master/Dockerfile.sidecar).

I scheduled it for the next major release `0.3.0`, but I'd be happy to review and merge a PR that fixes it sooner. :smile:

**Comment by surajssd** [comment]
@AMecea added a PSP config setup in https://github.com/presslabs/docker-orchestrator/pull/5 now will add the configs for mysql-operator.

**Comment by surajssd** [comment]
Add PSP configs for this chart https://github.com/presslabs/mysql-operator/pull/273

**Comment by surajssd** [comment]
The mysql pods that are started by the pod also need root in them to run, I had to give following PSP to the cluster pods

```yaml
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: mysql-cluster
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
spec:
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - KILL
  - MKNOD
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  - 'persistentVolumeClaim'
  - 'hostPath'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
    # Forbid adding the root group.
    - min: 1
      max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
    # Forbid adding the root group.
    - min: 1
      max: 65535
  readOnlyRootFilesystem: false
```
