### ISSUE TITLE
Introduce the concept of target SLOs

### ISSUE THREAD

**Issue by calind** [presslabs/mysql-operator#33]
For example, the cluster spec should specify that any slave lag is at most X seconds. We can use this it take the node out of rotation or automatically acknowledge node recovery in orchestrator. 

```yaml
spec:
  targetSLO:
    maxSlaveLatency: 10s
```
