### ISSUE TITLE
Add support for pt-kill

### ISSUE THREAD

**Issue by calind** [presslabs/mysql-operator#34]
https://www.percona.com/doc/percona-toolkit/LATEST/pt-kill.html

We should expose some parameters in `spec`. Maybe couple it with #33.

```yaml
spec:
  targetSLO:
    queryLimits:
      maxIdleTime: ...                # pt-kill --idle-time
      maxQueryTime: ...               # pt-kill --busy-time
      kill: oldest|all|all-but-oldest # pt-kill --victims
      killMode: query|connection      # pt-kill --kill-query or pt-kill --kill
      ignoreDb: []                    # pt-kill --ignore-db ...
      ignoreCommand: []               # pt-kill --ignore-command ...
      ignoreUser: []                  # pt-kill --ignore-user
```
