### ISSUE TITLE
does parameter replicate_ignore_wild_table support?

### ISSUE THREAD

**Issue by Jacklli** [presslabs/mysql-operator#340]
may i ask does parameter replicate_ignore_wild_table support on this mysql-operator？
thanks

**Comment by AMecea** [comment]
Hi @Jacklli, sure it can be used, for example in the MySQLCluster specification under `mysqlConf` you can add it, for example:
```yaml
spec:
  mysqlConf:
    replicate-wild-ignore-table: sys_operator.%
```

Do you have a specific usecase that didn't worked with the mysql-operator? Please let me know!
