### ISSUE TITLE
Restore a running mysql cluster

### ISSUE THREAD

**Issue by cpanato** [presslabs/mysql-operator#390]
Hello
I did the following thing:
1- create a mysql cluster without a database using this sample manifest
```yaml
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mm1
spec:
  replicas: 1
  secretName: test
  volumeSpec:
    persistentVolumeClaim:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
```
2- wait for the the pod be healthy
3- updated the manifest to use a backup and apply the restore
```yaml
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mm1
spec:
  replicas: 1
  secretName: test

  initBucketURL: s3://xxxxoooooxxxxooooo/backup11.gz
  initBucketSecretName: test-restore
  volumeSpec:
    persistentVolumeClaim:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
```
I saw the pos was in terminating state and then it start a new one, however the backup was not applied.

Does this is possible to achieve? 

cc @AMecea
