### ISSUE TITLE
create /etc/rclone.conf: Permission denied

### ISSUE THREAD

**Issue by majian159** [presslabs/mysql-operator#449]
init container error.

message:
```
Create rclone.conf file.
/usr/local/bin/docker-entrypoint.sh: line 6: can't create /etc/rclone.conf: Permission denied
```

**Comment by AMecea** [comment]
Hi @majian159, can you give me more details about the environment and what custom settings did you use and what version of the operator? Thank you!

**Comment by majian159** [comment]
mysql-operator version 0.3.1

my resources
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  # root password is required to be specified
  ROOT_PASSWORD: bm90LXNvLXNlY3VyZQ==
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-cluster
spec:
  replicas: 2
  secretName: my-secret
```

![image](https://user-images.githubusercontent.com/10176784/72230354-b5192000-35ef-11ea-9eba-23c0f533a38c.png)
