### ISSUE TITLE
Set backupURI into MysqlBackup spec field

### ISSUE THREAD

**Issue by calind** [presslabs/mysql-operator#48]
The controller should write backup final URI into `status` field of the `MysqlBackup` object, and that should be the source of truth regarding the backup location.

```yaml
kind: MysqlBackup
spec:
  cluster: ...
status:
  backupURI: gs://...
  backupTime: 2018-05-02T16:04:00Z
  complete: true
```
