### ISSUE TITLE
Q: orchestrator failover defaults

### ISSUE THREAD

**Issue by chasebolt** [presslabs/mysql-operator#482]
I am interested to know why these two settings in the mysql-cluster chart are not set to the defaults that orchestrator recommends. Currently killing the master mysql pod (db-0) promotes the slave (db-1) but then db-0 does not rejoin back correctly and is unable to be fixed. Setting `ApplyMySQLPromotionAfterMasterFailover: true` corrects this issue. I am sure setting to `false` is intended, just trying to understand why that is.

charts/mysql-cluster/values.yaml
```yaml
# `reset slave all` and `set read_only=0` on promoted master
ApplyMySQLPromotionAfterMasterFailover: false
MasterFailoverDetachReplicaMasterHost: true
```

orchestrator defaults listed in the docs:
```yaml
ApplyMySQLPromotionAfterMasterFailover: true
MasterFailoverDetachReplicaMasterHost: false
```
