### ISSUE TITLE
Sync status from orchestrator

### ISSUE THREAD

**Issue by calind** [presslabs/mysql-operator#51]
We should sync the cluster status from orchestrator:
```yaml
status:
  nodes:
    - name: mysql-0
      conditions:
        - type: lagged
          status: true/false/unknown
          lastTransitionStatus: 2018-...
        - type: replicating
          status: true/false/unknown
          lastTransitionStatus: 2018-...
        - type: master
          status: true/false/unknown
          lastTransitionStatus: 2018-...
      ...
  conditions:
    - type: pendingFailoverAck
      status: true/false/unknown
      lastTransitionStatus: 2018-...
```
