### ISSUE TITLE
[Quetion] Do we support to setup multi-master?

### ISSUE THREAD

**Issue by JasperHot** [presslabs/mysql-operator#519]
I have deployed 2 replicas via presslabs/mysql-operator, one is master and another is read-only. Do we support multi-master? Thanks.

**Comment by delgod** [comment]
Hi @JasperHot 
Presslabs Operator designed for async replication, it has its own benefits like write performance.
If you need the synchronous replication (master-master), you can consider using [Oracle Operator](https://github.com/oracle/mysql-operator) or [Percona Operator](https://github.com/percona/percona-xtradb-cluster-operator).

**Comment by albertyfwu** [comment]
@delgod Is it possible to enable semi-sync replication?

**Comment by AMecea** [comment]
Hi @albertyfwu, it should be possible, Here is the official MySQL documentation: https://dev.mysql.com/doc/refman/5.7/en/replication-semisync-installation.html. The operator supports enabling custom plugins but does not support different configurations for master or slave.

The only issue that I can see is that mysqld configuration should be different on the slave than on master but this is easy to implement.

**Comment by stankevich** [comment]
@albertyfwu: we've been running with semisynchronous replication for quite a while now. A few things to be aware of:

- To enable semisync, two plugins need to be loaded via `plugin_load`/`plugin_load_add` options, which take a semicolon-separated list of values: `plugin_load = semisync_master.so;semisync_slave.so`. Not a problem when you only need to load two plugins:

    ```yaml
    plugin-load: semisync_master.so
    plugin-load-add: semisync_slave.so
    ```

   This won't work if you need more than two plugins. The operator uses https://github.com/go-ini/ini to generate `my.cnf` from the cluster spec. However, `go-ini` treats semicolons as comments by default, so values with semicolons don't make it to `my.cnf`. Can be fixed in the operator, see https://github.com/go-ini/ini/issues/248. Use colons as a workaround in the meantime:

   ```yaml
    plugin-load: query_response_time.so:semisync_master.so:semisync_slave.so
   ```

- Disable `slave_compressed_protocol`, otherwise it breaks semisync. See https://bugs.mysql.com/bug.php?id=85382.
- We apply both master and replica settings everywhere for simplicity. The only minor thing with this approach is `rpl_semi_sync_master_no_tx` (the number of commits that haven't been successfully acknowledged by a replica) keeps increasing on all replicas (as nothing replicates from them). Adjust your monitoring accordingly.

Here's our configuration if it helps:

```yaml
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: example-cluster
spec:
  mysqlConf:
    plugin-load: semisync_master.so:semisync_slave.so
    rpl-semi-sync-master-enabled: 1
    rpl-semi-sync-master-timeout: 1000
    rpl-semi-sync-master-wait-for-slave-count: 1
    rpl-semi-sync-slave-enabled: 1
    slave-compressed-protocol: "off"
```
