### ISSUE TITLE
backup support object storage of ali oss

### ISSUE THREAD

**Issue by Erically** [presslabs/mysql-operator#548]

**Comment by AMecea** [comment]
Hi @Erically, thank you for your suggestion! I see that [Rclone already supports Ali OSS](https://rclone.org/s3/#alibaba-oss), so the implementation should be straight forward. Please feel free to open a PR with this feature I will be happy to review and merge it.

**Comment by AMecea** [comment]
I think that this is possible without any changes. I just need testing.

Allyun OSS is S3 compatible so you just have to define your [backup secret](https://github.com/presslabs/mysql-operator/blob/master/examples/example-backup-secret.yaml) as describe in [Rclone documentation](https://rclone.org/s3/#alibaba-oss) and the coniguration template can be found [here](https://github.com/presslabs/mysql-operator/blob/master/hack/docker/sidecar-entrypoint.sh#L6):
```
apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-backup-secret
type: Opaque
data:
    S3_PROVIDER: Alibaba
    AWS_ACCESS_KEY_ID: # your access key id
    AWS_SECRET_ACCESS_KEY: # your secret key
    S3_ENDPOINT: # one of: oss-cn-hangzhou.aliyuncs.com, oss-cn-shanghai.aliyuncs.com, oss-cn-qingdao.aliyuncs.com
    AWS_ACL: private
    AWS_STORAGE_CLASS: Standard
    # AWS_REGION: ?
```

You have to set AWS_REGION to your bucket region right now is set to `us-east-1`.

So, your [bucketURL](https://github.com/presslabs/mysql-operator/blob/master/examples/example-cluster.yaml#L22) should be something like `s3://sample-demo-bucket/mysql_cluster_backups/`

Please let me know if this works!
