### ISSUE TITLE
[feature request] Restore from public HTTP link

### ISSUE THREAD

**Issue by abdennour** [presslabs/mysql-operator#584]
I have a MySQL dump uploaded to one of file sharing services.

I have the HTTP link of this backup.

I want to create a restore from this HTTP link .

As per examples, I can see only one source type which is  `initBucketURL`  (S3, or GS).

Is it possible to restore from HTTP link  ?

Something like this: 

```yaml
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: restore-2020-08-04
spec:
  initBucketURL: https://files.example.com/backups/db-a.sql.gz
```
