### ISSUE TITLE
Problem when master node dies second time

### ISSUE THREAD

**Issue by AlexTr** [presslabs/mysql-operator#608]
When master pod `my-cluster-mysql-0` dies, then `my-cluster-mysql-[1-9]` becomes master pod. Then if cluster is resized to 1 replica, then master node `my-cluster-mysql-1`  is deleted, and cluster stays with one `my-cluster-mysql-0` pod which become master, so first time this works fine. Then when we do the same second time, we have `my-cluster-mysql-0` pod which is configured as slave.

# Steps to reproduce:
```
% kubectl get pods -n ns
NAME                              READY   STATUS    RESTARTS   AGE
my-cluster-mysql-0                4/4     Running   0          47h
my-cluster-mysql-1                4/4     Running   0          9m34s
my-cluster-mysql-2                4/4     Running   0          8m47s
```
```
 % kubectl describe pod my-cluster-mysql-0 -n ns | grep role
              role=master
```
```
% kubectl delete pod my-cluster-mysql-0 -n ns
pod "my-cluster-mysql-0" deleted
```
```
% kubectl describe pod my-cluster-mysql-0 -n ns | grep role
              role=replica
% kubectl describe pod my-cluster-mysql-1 -n ns | grep role
              role=replica
% kubectl describe pod my-cluster-mysql-2 -n ns | grep role
              role=master
```
Resize cluster by changing replicas to `1`:
```yaml
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-cluster
  namespace: ns
spec:
  replicas: 1
  ...
```
and apply changes:
```
% kubectl apply -f ./k8s/operator/mysql-cluster.yaml
mysqlcluster.mysql.presslabs.org/my-cluster configured
```
```
% kubectl get pods -n ns
NAME                              READY   STATUS        RESTARTS   AGE
my-cluster-mysql-0                4/4     Running       0          7m6s
```
Now everything is fine:
```
% kubectl describe pod my-cluster-mysql-0 -n ns | grep role
              role=master
```
Now resize to 2 pods:
```yaml
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-cluster
  namespace: ns
spec:
  replicas: 2
  ...
```
```
% kubectl apply -f ./k8s/operator/mysql-cluster.yaml           
mysqlcluster.mysql.presslabs.org/my-cluster configured
```
```
% kubectl get pods -n ns                                   
NAME                              READY   STATUS    RESTARTS   AGE
my-cluster-mysql-0                4/4     Running   0          12m
my-cluster-mysql-1                3/4     Running   0          39s
```
```
% kubectl describe pod my-cluster-mysql-0 -n ns | grep role
              role=master
% kubectl describe pod my-cluster-mysql-1 -n ns | grep role
              role=replica
```
And delete master node again:
```
% kubectl delete pod my-cluster-mysql-0 -n ns      
pod "my-cluster-mysql-0" deleted
```
```
% kubectl describe pod my-cluster-mysql-1 -n ns | grep role
              role=master
% kubectl describe pod my-cluster-mysql-0 -n ns | grep role
              role=replica
```

Now resize to 1:

```yaml
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-cluster
  namespace: ns
spec:
  replicas: 1
  ...
```
```
% kubectl get pods -n ns
NAME                              READY   STATUS    RESTARTS   AGE
my-cluster-mysql-0                4/4     Running   0          117s
```
```
% kubectl describe pod my-cluster-mysql-0 -n ns | grep role
              role=replica
```
As the result we have non working cluster with one pod which is configured as slave and can't connect to the master:
```
% kubectl logs my-cluster-mysql-0 mysql -n ns
2020-09-17T13:27:37.183833Z 219 [ERROR] Slave I/O for channel '': error connecting to master 'sys_replication@//my-cluster-mysql-1.mysql.ns:3306' - retry-time: 1  retries: 331, Error_code: 2005
```
