### ISSUE TITLE
Guide to setup prometheus monitoring 

### ISSUE THREAD

**Issue by Rahulsharma0810** [presslabs/mysql-operator#609]
Can you guide me through, collecting metrics in Prometheus, I can see port 9125 on, NONE cluster IP.
```
NAME                               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
mysql                              ClusterIP   None            <none>        3306/TCP,9125/TCP   23h
mysql-operator                     ClusterIP   10.103.18.76    <none>        80/TCP              23h
mysql-operator-0-svc               ClusterIP   10.102.89.0     <none>        80/TCP,10008/TCP    23h
mysql-ops-cluster-mysql            ClusterIP   10.97.204.135   <none>        3306/TCP            66m
mysql-ops-cluster-mysql-master     ClusterIP   10.102.106.38   <none>        3306/TCP,8080/TCP   66m
mysql-ops-cluster-mysql-replicas   ClusterIP   10.97.101.177   <none>        3306/TCP,8080/TCP   66m
```

How to export this metic and what is the value for `scrape_configs`

Thanks,
Rahul Sharma

**Comment by AMecea** [comment]
Hi, @Rahulsharma0810, 

Yes you can set a Prometheus ServiceMonitor resource to collect logs from that port. I've played more with PodMonitor to select all mysql pods and collect logs from that port.

Here is an example of PodMonitor resource:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: monitor-mysql-pods
  namespace: monitoring
  labels:
    # your labels here
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: mysql.presslabs.org
  podMetricsEndpoints:
  - port: "prometheus"
```

Can I see description of your ServiceMonitor resource?
