### ISSUE TITLE
【Offline installation】Failed to pull image "percona@sha256:713c1817615b333b17d....."

### ISSUE THREAD

**Issue by lefeiwang** [presslabs/mysql-operator#616]
[Offline installation]
During offline installation, there is no way to download such an offline mirror. How to replace the mirror with a version number for installation.

**Comment by AMecea** [comment]
Hi @lefeiwang,

You can at any time specifying the MySQL server image by settings [`image` field](https://github.com/presslabs/mysql-operator/blob/d9a3f08a13831472fa202a841de5eae7f926114d/examples/example-cluster.yaml#L11) on the `MysqlCluster` resource. See this example:
```yaml
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-cluster
spec:
  replicas: 2
  secretName: my-secret
  image: your-mirror-percona:5.7
```
 
Please let me know if this helps!
