### ISSUE TITLE
Change TimeZone

### ISSUE THREAD

**Issue by sritter-sellvin** [presslabs/mysql-operator#621]
Hi Guyes,

is it possible to change the timezone to Europe/Berlin in helm?

We are using helm to deploy the mysql-cluster as following:
```yaml
replicas: 2

[...]

mysqlConf:
  default-time-zone: "+02:00"

[...]
```

Currently we are setting the default-time-zone to "+02:00". Last weekend we changed from summer to winter time and it would be "+01:00", so it is easier to use "Europe/Berlin".

Thanks a lot!

**Comment by AMecea** [comment]
Hi @sritter-sellvin, thank you for using the operator!

What do you mean by setting the timezone in helm?

**Comment by sritter-sellvin** [comment]
Hi @AMecea!

For deploying our mysql-cluster we are using helmfile that includes a values.yaml.
The helmfile looks like:

``` yaml
repositories:
  - name: presslabs
    url: https://presslabs.github.io/charts

releases:
  - name: mysql-cluster
    namespace: xyz
    chart: presslabs/mysql-cluster
    version: 0.2.0
    values:
      - values-mysql.yaml
```

The values-mysql.yaml looks like:
``` yaml
replicas: 2

rootPassword: "rootPassword"

mysqlConf:
  default-time-zone: "+01:00"

podSpec:
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1G
      cpu: 500m

volumeSpec:
  persistentVolumeClaim:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 5Gi
```

With mysqlConf is it possible to set some values to the my.cnf, right?
So we would to set the default-time-zone to "Europe/Berlin" instead of "+1:00" (or "+02:00" in summertime) but that doesen´t work. (https://dev.mysql.com/doc/refman/5.7/en/time-zone-support.html)
``` yaml
mysqlConf:
  default-time-zone: "Europe/Berlin"
```

In our Nodes we change the timezone with a DaemonSet including a volumeMount and a command.
Maybe it is possible to use the node timezone in the mysql-cluster / mysql-operator?
``` yaml
- command:
        - sh
        - -c
        - |
          cp /mnt/timezone/Berlin /mnt/localtime/localtime

  volumeMounts:
     - mountPath: /mnt/localtime
       name: localtime
     - mountPath: /mnt/timezone
        name: timezone

volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Europe
        - name: localtime
          hostPath:
            path: /etc
```

**Comment by sritter-sellvin** [comment]
Now we got the solution.

To change the timezone you need to add a new container like following:
```yaml
containers:
    - name: change-timezone
      image: mysql:5.7
      env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      args:
        - |
          while true; do
            sleep 100000;
          done
      command:
        - sh
        - -c
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - -c
              - "mysql -u yourUser -p'yourPassword' -h $MY_POD_NAME -e \"SET GLOBAL time_zone = 'Europe/Berlin'\""
```
