### ISSUE TITLE
PersistenteVolume deleting when stopping the pod

### ISSUE THREAD

**Issue by enoliveira** [presslabs/mysql-operator#646]
This is my yaml file:
```
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: {{ .Values.magento_database_cluster.name }} 
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  secretName: magento-database-users 
  initBucketURL: {{ .Values.magento_database.backup }}
  initBucketSecretName: mysql-database-storage-secret  
  volumeSpec:
    persistentVolumeClaim:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 15Gi
  backupCompressCommand:
    - pigz
    - --stdout  
  backupDecompressCommand:
    - gzip 
  rcloneExtraArgs:
    - --buffer-size=1G
    - --multi-thread-streams=8
    - --retries-sleep=10s
    - --retries=10
```
Every time I stop the pod the volume is getting deleted. It creates the persistenteVolume and  persistenteVolumeClaim. 

Using: minikube + skaffold + helm 3 
![image](https://user-images.githubusercontent.com/44368472/104070455-ef060d80-51d4-11eb-9858-33525c1bf8ff.png)

Am I missing something? 

Thanks
