### ISSUE TITLE
Cluster creating fails with "sidecar service was not available"

### ISSUE THREAD

**Issue by munjalpatel** [presslabs/mysql-operator#653]
Hello,

I am trying to setup a simple 3 node mysql cluster.
However, it keeps failing with the following log in the `init` container of the 2nd stateful set pod:
_1st pod of the stateful set does come online fine_

```
Create rclone.conf file.
1/30/2021 4:06:57 PM 2021-01-31T00:06:57.484330358Z	INFO	sidecar	environment is not set	{"key": "MY_SERVER_ID_OFFSET"}
1/30/2021 4:06:57 PM 2021-01-31T00:06:57.484406759Z	INFO	sidecar	environment is not set	{"key": "INIT_BUCKET_URI"}
1/30/2021 4:06:57 PM 2021-01-31T00:06:57.48441406Z	INFO	sidecar	environment is not set	{"key": "RCLONE_EXTRA_ARGS"}
1/30/2021 4:06:57 PM 2021-01-31T00:06:57.48441786Z	INFO	sidecar	environment is not set	{"key": "XBSTREAM_EXTRA_ARGS"}
1/30/2021 4:06:57 PM 2021-01-31T00:06:57.48442466Z	INFO	sidecar	environment is not set	{"key": "XTRABACKUP_EXTRA_ARGS"}
1/30/2021 4:06:57 PM 2021-01-31T00:06:57.48442896Z	INFO	sidecar	environment is not set	{"key": "XTRABACKUP_PREPARE_EXTRA_ARGS"}
1/30/2021 4:06:57 PM 2021-01-31T00:06:57.48443326Z	INFO	sidecar	environment is not set	{"key": "XTRABACKUP_TARGET_DIR"}
1/30/2021 4:06:57 PM 2021-01-31T00:06:57.48443716Z	INFO	sidecar	environment is not set	{"key": "INITFILE_EXTRA_SQL"}
1/30/2021 4:06:57 PM 2021-01-31T00:06:57.48447076Z	INFO	sidecar	cloning command	{"host": "my-dev-cluster-mysql-1"}
1/30/2021 4:06:58 PM 2021-01-31T00:06:58.517420291Z	INFO	sidecar	service was not available	{"service": "my-dev-cluster-mysql-replicas", "error": "Get http://my-dev-cluster-mysql-replicas:8080/health: dial tcp 10.10.10.214:8080: connect: connection refused"}
1/30/2021 4:06:59 PM 2021-01-31T00:06:59.541378169Z	INFO	sidecar	service was not available	{"service": "my-dev-cluster-mysql-master", "error": "Get http://my-dev-cluster-mysql-master:8080/health: dial tcp 10.10.10.97:8080: connect: connection refused"}
1/30/2021 4:06:59 PM 2021-01-31T00:06:59.54144527Z	ERROR	sidecar	clone command failed	{"error": "nothing to clone from: no existing data found, no replicas and no master available, and no clone bucket url found"}
1/30/2021 4:06:59 PM github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error
1/30/2021 4:06:59 PM 	/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:128
1/30/2021 4:06:59 PM main.main.func2
1/30/2021 4:06:59 PM 	/go/src/github.com/presslabs/mysql-operator/cmd/mysql-operator-sidecar/main.go:67
1/30/2021 4:06:59 PM github.com/presslabs/mysql-operator/vendor/github.com/spf13/cobra.(*Command).execute
1/30/2021 4:06:59 PM 	/go/src/github.com/presslabs/mysql-operator/vendor/github.com/spf13/cobra/command.go:766
1/30/2021 4:06:59 PM github.com/presslabs/mysql-operator/vendor/github.com/spf13/cobra.(*Command).ExecuteC
1/30/2021 4:06:59 PM 	/go/src/github.com/presslabs/mysql-operator/vendor/github.com/spf13/cobra/command.go:852
1/30/2021 4:06:59 PM github.com/presslabs/mysql-operator/vendor/github.com/spf13/cobra.(*Command).Execute
1/30/2021 4:06:59 PM 	/go/src/github.com/presslabs/mysql-operator/vendor/github.com/spf13/cobra/command.go:800
1/30/2021 4:06:59 PM main.main
1/30/2021 4:06:59 PM 	/go/src/github.com/presslabs/mysql-operator/cmd/mysql-operator-sidecar/main.go:111
1/30/2021 4:06:59 PM runtime.main
1/30/2021 4:06:59 PM 	/usr/local/go/src/runtime/proc.go:203
```

Here is my cluster definition:

```yaml
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-dev-cluster
spec:
  replicas: 3
  secretName: my-dev-cluster
  maxUnavailable: 1
  backupSchedule: 0 * * * *
  backupURL: azure://azurestorageaccount
  backupSecretName: my-dev-cluster-azstore
  backupScheduleJobsHistoryLimit: 10
  podSpec:
    labels: 
      app: my-dev-cluster
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app: my-dev-cluster
    backupTolerations:
      - effect: NoSchedule
        key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
    resources:
      requests:
        memory: 256Mi
        cpu:    100m
      limits:
        memory: 512Mi
        cpu:    200m
    tolerations:
      - effect: NoSchedule
        key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
    priorityClassName: high-priority
  volumeSpec:
    persistentVolumeClaim:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
      storageClassName: "default"
```
