### ISSUE TITLE
 The MySQL server is running with the --super-read-only option

### ISSUE THREAD

**Issue by iogrids** [presslabs/mysql-operator#689]
I am running mysqlcluster with the below configuration

```
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mycluster
spec:
  mysqlVersion: "5.7"
  replicas: 2
  secretName: mycluster-secret
  mysqlConf:
    read_only: 0                          # mysql forms a single transaction for each sql statement, autocommit for each statement
    automatic_sp_privileges: "ON"         # automatically grants the EXECUTE and ALTER ROUTINE privileges to the creator of a stored routine
    auto_generate_certs: "ON"             # Auto Generation of Certificate
    auto_increment_increment: 1           # Auto Incrementing value from +1
    auto_increment_offset: 1              # Auto Increment Offset
    binlog-format: "STATEMENT"            # contains various options such ROW(SLOW,SAFE) STATEMENT(FAST,UNSAFE), MIXED(combination of both)
    wait_timeout: 31536000                # 28800 number of seconds the server waits for activity on a non-interactive connection before closing it, You might encounter MySQL server has gone away error, you then tweak this value acccordingly
    interactive_timeout: 28800            # The number of seconds the server waits for activity on an interactive connection before closing it.

```

but why is it I am getting this error

```
WordPress database error The MySQL server is running with the --super-read-only option so it cannot execute this statement for query DELETE
```
