### ISSUE TITLE
Feature request: Add global option to set podAntiAffinity on all MysqlClusters

### ISSUE THREAD

**Issue by haslersn** [presslabs/mysql-operator#711]
This is a feature request to add a global configuration option to MySQL operator to set a podAntiAffinity on all MysqlCluster Pods by default.

## Motivation

This feature would remove the boilerplate which we have due to our workaround (see below). It would also remove the redundancy of having to mention the MysqlCluster's name twice (see below, `example` appears twice).

## Workaround

Our current workaround is to add the following spec manually to every MysqlCluster:

```
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: example
spec:
  podSpec:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                mysql.presslabs.org/cluster: example
```

## Potential problems

- **Problem:** What if you configure a default podAntiAffinity in the operator and you want to have a single MysqlCluster (or a few of them) where you don't want the podAntiAffinity to be set?
  **Solution:** Maybe don't use the default podAntiAffinity if `MysqlCluster.spec.podSpec.affinity` is non-empty.
