### ISSUE TITLE
Delete backups from backupBucket when deleting a MysqlBackup

### ISSUE THREAD

**Issue by calind** [presslabs/mysql-operator#81]

**Comment by AMecea** [comment]
Use finalizers to block backup deletion until the backup is deleted from the remote.

Add a `.spec.deletePolicy` field. For example:
```
kind: MysqlBackup
spec:
  clusterName: foo
  deletePolicy: hardDelete / softDelete
```

Log failed deletion attempts in events. Also, it needs an exponential backup deletion retry.
