### ISSUE TITLE
Duplicate cluster name in different namespaces prevents cluster from being setup correctly

### ISSUE THREAD

**Issue by davidhiendl** [presslabs/mysql-operator#851]
When creating multiple clusters in **different namespaces** with the same name only one cluster is added to the orchestrator and one cluster remains in read-only mode.

Example: 
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-somename-auth
  namespace: test-1
type: Opaque
stringData:
  ROOT_PASSWORD: Test1

---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: somename
  namespace: test-1
spec:
  image: percona:8.0
  mysqlVersion: "8.0"
  replicas: 1
  secretName: mysql-somename-auth

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-somename-auth
  namespace: test-2
type: Opaque
stringData:
  ROOT_PASSWORD: Test2

---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: somename
  namespace: test-2
spec:
  image: percona:8.0
  mysqlVersion: "8.0"
  replicas: 1
  secretName: mysql-somename-auth
```
