### ISSUE TITLE
duplicate fields cannot be defined in the mysqlConf of the MysqlCluster resource.

### ISSUE THREAD

**Issue by usernameisnull** [presslabs/mysql-operator#931]
MySQL allow duplicate field, like`binlog_do_db`
```
[mysqld]
binlog_do_db            = db3
binlog_do_db            = db4
# other fields
```

in mysql we can get the result
```
mysql> show master status\G
*************************** 1. row ***************************
             File: binlog.000022
         Position: 157
     Binlog_Do_DB: db3,db4
 Binlog_Ignore_DB:
Executed_Gtid_Set:
1 row in set (0.00 sec)
```
---
but in MysqlCluster resource, mysqlConf field is a  map[string]string, not allowed to do this, if in IDE will warn us
```
spec:
  backupRemoteDeletePolicy: delete
  image: docker.m.daocloud.io/library/mysql:5.7.31
  mysqlConf:
    binlog-format: ROW
    binlog_do_db: db3
    binlog_do_db: db4
```
![image](https://github.com/user-attachments/assets/5a224375-96ac-4d26-9c98-339107e03741)

if we apply this cr, in running mysql,only one value
```
mysql> show master status\G
*************************** 1. row ***************************
             File: mysql-bin.000003
         Position: 154
     Binlog_Do_DB: db4
 Binlog_Ignore_DB:
Executed_Gtid_Set:
1 row in set (0.00 sec)
```
