### ISSUE TITLE
want to set resources in "init" container, have two "init" containers

### ISSUE THREAD

**Issue by usernameisnull** [presslabs/mysql-operator#935]
## the cr's yaml
```
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-cluster
spec:
  replicas: 1
  secretName: my-secret
  podSpec:
    initContainers:
      - name: init
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 107374182400m
```

## describe sts
```
Events:
  Type     Reason            Age                 From                    Message
  ----     ------            ----                ----                    -------
  Normal   SuccessfulCreate  74s                 statefulset-controller  create Claim data-ddd1218-init-3-mysql-0 Pod ddd1218-init-3-mysql-0 in StatefulSet ddd1218-init-3-mysql success
  Warning  FailedCreate      32s (x14 over 74s)  statefulset-controller  create Pod ddd1218-init-3-mysql-0 in StatefulSet ddd1218-init-3-mysql failed error: Pod "ddd1218-init-3-mysql-0" is invalid: [spec.initContainers[0].image: Required value, spec.initContainers[1].name: Duplicate value: "init"]
```

## the sts yaml
![image](https://github.com/user-attachments/assets/3b1f8cca-681e-4e7c-ab61-12914723f7b0)

```
